# Generated by Django 4.2.4 on 2023-08-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_artist_album_is_favorite_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
